<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="C100414" failures="1" tests="3" name="Surefire test" time="0.081" errors="0" timestamp="2019-11-11T11:52:06 EET">
  <testcase classname="samples.FirstTest" name="first" time="0.02"/>
  <testcase classname="samples.FirstTest" name="second" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [1] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [2]
at samples.FirstTest.second(FirstTest.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- second -->
  <testcase classname="samples.FirstTest" name="third" time="0.0"/>
</testsuite> <!-- Surefire test -->
